---
- name: Install project prerequisites

  hosts: localhost

  gather_facts: no

  tasks:

    - name: install requirements
      command: pip install -r requirements.txt

    - name: install galaxy roles
      command: ansible-galaxy install -r roles/requirements.yml -p roles/ --force
