---
all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      ansible_connection: local

kvm_hosts:
  hosts:
    localhost:

kvm_guests:
  hosts:
    kvma.wpnops.biz:
      kvm_profile: small
      hw_address: 7a:85:56:fb:6d:d0
      ansible_host: 10.50.19.90
      kvm_image: centos8
    kvmb.wpnops.biz:
      kvm_profile: small
      hw_address: 7a:85:56:fb:6d:d0
      ansible_host: 10.50.19.91
      kvm_image: centos8
    kvmc.wpnops.biz:
      kvm_profile: small
      hw_address: 7a:85:56:fb:6d:d0
      ansible_host: 10.50.19.92
      kvm_image: centos8
    kvmd.wpnops.biz:
      kvm_profile: large
      hw_address: 7a:85:56:fb:6d:d0
      ansible_host: 10.50.19.93
      kvm_image: centos8
    kvme.wpnops.biz:
      kvm_profile: large
      hw_address: 7a:85:56:fb:6d:d0
      ansible_host: 10.50.19.94
      kvm_image: centos8
    kvmf.wpnops.biz:
      kvm_profile: large
      hw_address: 7a:85:56:fb:6d:d0
      ansible_host: 10.50.19.95
      kvm_image: centos8
